### ISSUE TITLE
vanityPattern ?

### ISSUE THREAD

**Issue by talpih** [bernardladenthin/BitcoinAddressFinder#26]
hi
in the default example file there is a 
"vanityPattern" : "1[Ee][Mm][Ii][Ll].*"

does it limit to addresses that prefix those only? should I remove that?

**Comment by bernardladenthin** [comment]
Hi,

https://github.com/bernardladenthin/BitcoinAddressFinder/blob/8c69963701adb2843415f88e0fbc21a56de0d3e6/examples/config_Find_1OpenCLDevice.js#L16

https://github.com/bernardladenthin/BitcoinAddressFinder/blob/8c69963701adb2843415f88e0fbc21a56de0d3e6/src/main/java/net/ladenthin/bitcoinaddressfinder/ConsumerJava.java#L252

The example file has a pattern but the *additional* pattern matching is deactivated because it slow down the finding process. It is a hybrid mode to look for vanity addresses during address finding. It is a hybrid mode and does not affect the address search in general. It looks out for vanity addresses in addition because the EC-Key generation is calculcation cost intensive and can be used for vanity addresses also.

You can test this mode easily if you type a short pattern of your choice and see that you have some vanity hits.
